language: python
python:
  - "3.7.4"
install:
  - pip install 'jaconv==0.2.4'
  - pip install 'Janome==0.3.9'
  - pip install 'pyttsx3==2.71'
  - pip install 'wikipedia-api==0.5.4'
  - pip install 'Pillow==7.2.0'
  - pip install 'requests==2.24.0'
dist: xenial
services:
  - xvfb
script:
  - python ./source/novel_editor.py test